name: Build and Test
on: [push]
jobs:
  run-container:
    name: End to End
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Install rust-to-npm CLI"
        run: cd cli && cargo install  --path .
      - name: "Run rust-to-npm"
        run: cd rust-to-npm && rust-to-npm-cli build && cat ./package.json
